"use client";

import React from "react";

type Difficulty = "peaceful" | "easy" | "normal" | "hard";
type GameMode = "survival" | "creative" | "adventure" | "spectator";

export default function Home() {
  const [serverName, setServerName] = React.useState("My Minecraft Server");
  const [difficulty, setDifficulty] = React.useState<Difficulty>("normal");
  const [gameMode, setGameMode] = React.useState<GameMode>("survival");
  const [maxPlayers, setMaxPlayers] = React.useState(20);
  const [pvp, setPvp] = React.useState(true);
  const [hardcore, setHardcore] = React.useState(false);
  const [onlineMode, setOnlineMode] = React.useState(true);
  const [copied, setCopied] = React.useState(false);

  const config = `# Generated by Minecraft Server Config Generator
motd=${serverName}
difficulty=${difficulty}
gamemode=${gameMode}
max-players=${maxPlayers}
pvp=${pvp}
hardcore=${hardcore}
online-mode=${onlineMode}
enable-command-block=false
spawn-protection=16
view-distance=10
simulation-distance=10
`;

  async function copyConfig() {
    await navigator.clipboard.writeText(config);
    setCopied(true);

    setTimeout(() => {
      setCopied(false);
    }, 1500);
  }

  function downloadConfig() {
    const blob = new Blob([config], { type: "text/plain" });
    const url = URL.createObjectURL(blob);

    const link = document.createElement("a");
    link.href = url;
    link.download = "server.properties";
    link.click();

    URL.revokeObjectURL(url);
  }

  return (
    <main className="min-h-screen bg-zinc-950 px-6 py-10 text-zinc-50">
      <div className="mx-auto max-w-6xl">
        <section className="mb-10">
          <p className="mb-3 inline-flex rounded-full border border-zinc-800 bg-zinc-900 px-4 py-2 text-sm text-emerald-300">
            Minecraft Tool • React • TypeScript
          </p>

          <h1 className="max-w-3xl text-4xl font-bold tracking-tight sm:text-6xl">
            Minecraft Server Config Generator
          </h1>

          <p className="mt-4 max-w-2xl text-lg leading-relaxed text-zinc-300">
            Generate a clean <span className="text-zinc-100">server.properties</span>{" "}
            file for your Minecraft server using a simple interactive form.
          </p>
        </section>

        <section className="grid gap-6 lg:grid-cols-2">
          <div className="rounded-2xl border border-zinc-800 bg-zinc-900/50 p-6">
            <h2 className="mb-5 text-xl font-semibold">Server Settings</h2>

            <div className="space-y-5">
              <label className="block">
                <span className="mb-2 block text-sm text-zinc-300">
                  Server Name / MOTD
                </span>
                <input
                  value={serverName}
                  onChange={(e) => setServerName(e.target.value)}
                  className="w-full rounded-xl border border-zinc-800 bg-zinc-950 px-4 py-3 text-zinc-100 outline-none transition focus:border-emerald-500"
                  placeholder="My Minecraft Server"
                />
              </label>

              <label className="block">
                <span className="mb-2 block text-sm text-zinc-300">
                  Difficulty
                </span>
                <select
                  value={difficulty}
                  onChange={(e) => setDifficulty(e.target.value as Difficulty)}
                  className="w-full rounded-xl border border-zinc-800 bg-zinc-950 px-4 py-3 text-zinc-100 outline-none transition focus:border-emerald-500"
                >
                  <option value="peaceful">Peaceful</option>
                  <option value="easy">Easy</option>
                  <option value="normal">Normal</option>
                  <option value="hard">Hard</option>
                </select>
              </label>

              <label className="block">
                <span className="mb-2 block text-sm text-zinc-300">
                  Game Mode
                </span>
                <select
                  value={gameMode}
                  onChange={(e) => setGameMode(e.target.value as GameMode)}
                  className="w-full rounded-xl border border-zinc-800 bg-zinc-950 px-4 py-3 text-zinc-100 outline-none transition focus:border-emerald-500"
                >
                  <option value="survival">Survival</option>
                  <option value="creative">Creative</option>
                  <option value="adventure">Adventure</option>
                  <option value="spectator">Spectator</option>
                </select>
              </label>

              <label className="block">
                <span className="mb-2 block text-sm text-zinc-300">
                  Max Players
                </span>
                <input
                  type="number"
                  min={1}
                  max={200}
                  value={maxPlayers}
                  onChange={(e) => setMaxPlayers(Number(e.target.value))}
                  className="w-full rounded-xl border border-zinc-800 bg-zinc-950 px-4 py-3 text-zinc-100 outline-none transition focus:border-emerald-500"
                />
              </label>

              <div className="grid gap-3 sm:grid-cols-3">
                <Toggle label="PvP" checked={pvp} onChange={setPvp} />
                <Toggle
                  label="Hardcore"
                  checked={hardcore}
                  onChange={setHardcore}
                />
                <Toggle
                  label="Online Mode"
                  checked={onlineMode}
                  onChange={setOnlineMode}
                />
              </div>
            </div>
          </div>

          <div className="rounded-2xl border border-zinc-800 bg-zinc-900/50 p-6">
            <div className="mb-5 flex flex-wrap items-center justify-between gap-3">
              <h2 className="text-xl font-semibold">Generated Output</h2>

              <div className="flex gap-2">
                <button
                  onClick={copyConfig}
                  className="rounded-xl bg-white px-4 py-2 text-sm font-medium text-zinc-950 transition hover:opacity-90"
                >
                  {copied ? "Copied!" : "Copy"}
                </button>

                <button
                  onClick={downloadConfig}
                  className="rounded-xl border border-zinc-700 px-4 py-2 text-sm font-medium text-zinc-100 transition hover:bg-zinc-800"
                >
                  Download
                </button>
              </div>
            </div>

            <pre className="min-h-[420px] overflow-auto rounded-xl border border-zinc-800 bg-zinc-950 p-4 text-sm leading-relaxed text-emerald-200">
              <code>{config}</code>
            </pre>
          </div>
        </section>

        <footer className="mt-10 text-sm text-zinc-500">
          Built with Next.js, React, TypeScript and Tailwind CSS.
        </footer>
      </div>
    </main>
  );
}

function Toggle({
  label,
  checked,
  onChange,
}: {
  label: string;
  checked: boolean;
  onChange: (value: boolean) => void;
}) {
  return (
    <button
      type="button"
      onClick={() => onChange(!checked)}
      className={`rounded-xl border px-4 py-3 text-left transition ${
        checked
          ? "border-emerald-500 bg-emerald-500/10 text-emerald-200"
          : "border-zinc-800 bg-zinc-950 text-zinc-300"
      }`}
    >
      <span className="block text-sm font-medium">{label}</span>
      <span className="mt-1 block text-xs">{checked ? "Enabled" : "Disabled"}</span>
    </button>
  );
}